# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Project
group=de.cech12.ceramicbucket
mod_version=6.0.0.0
mod_id=ceramicbucket
mod_name=Ceramic Bucket
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/CeramicBucket
mod_issue_tracker=https://github.com/cech12/CeramicBucket/issues
description=A mod which adds a Ceramic Bucket.

# Common
java_version=21
minecraft_version=1.21
minecraft_version_range=[1.21, 1.22)

# Fabric
fabric_version=0.100.3+1.21
fabric_loader_version=0.15.11
cloth_config_version=15.0.127
mod_menu_version=11.0.0

# Forge
forge_version=51.0.16
forge_version_range=[51.0.16,)
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.20-beta
neoforge_version_range=[21.0.20-beta,)
neoforge_loader_version_range=[2,)

#Bucket Lib
bucketlib_version=1.21-4.0.0.1
bucketlib_version_range=[1.21-4.0.0.1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false