# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
group=de.cech12.ceramicbucket
mod_version=7.0.0.0
mod_id=ceramicbucket
mod_name=Ceramic Bucket
mod_author=Cech12
mod_license=The MIT License (MIT)
mod_url=https://github.com/cech12/CeramicBucket
mod_issue_tracker=https://github.com/cech12/CeramicBucket/issues
description=A mod which adds a Ceramic Bucket.

# Common
java_version=25
minecraft_version=26.1
minecraft_version_range=[26.1, 27)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric
fabric_version=0.145.1+26.1
fabric_loader_version=0.18.5
cloth_config_version=26.1.154
mod_menu_version=18.0.0-alpha.8

# Forge
# net.minecraftforge.gradle.merge-source-sets=true
# forge_version=53.0.7
# forge_loader_version_range=[51,)

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[2,)

#Bucket Lib
bucketlib_version=26.1-5.0.0.0
bucketlib_version_range=[26.1-5.0.0.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false